version: 2.1
orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Check docker"
          shell: powershell.exe
          command: |
            docker info
            docker run -v ${PWD}:C:\src -w C:\src python:3.8-windowsservercore-1809 powershell .\build.ps1
      - store_artifacts:
          path: ~/project/dist
  test:
    working_directory: ~/adsorptioninformationformat
    docker:
      - image: circleci/python:3.8.0
    steps:
      - checkout
      - run:
          name: Setup Miniconda
          command: |
            sudo apt update
            sudo apt install -y wget
            cd $HOME
            wget "https://repo.anaconda.com/miniconda/Miniconda3-4.7.10-Linux-x86_64.sh" -O miniconda.sh
            printf '%s' "8a324adcc9eaf1c09e22a992bb6234d91a94146840ee6b11c114ecadafc68121  miniconda.sh" | sha256sum -c
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Setup environment and run tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda update -y conda
            conda create -n myenv python=$PYTHON_VERSION -c conda-forge
            source activate myenv
            conda install pytest
            pip install -r requirements.txt
            python -m pytest ~/adsorptioninformationformat/test
      - store_artifacts:
          path: /tmp/test-reports
          destination: ~/adsorptioninformationformat

workflows:
  version: 2.1
  main:
    jobs:
    - test
    - build:
        filters:
          branches:
            only: master